config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :site_users
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resource :site_bot, only: [:create, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pay_code.rb
class PayCode < ApplicationRecord
  belongs_to :site_bot
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :site_bot
  has_many :treasures, dependent: :destroy
end

app/models/site_bot.rb
class SiteBot < ApplicationRecord
  belongs_to :site_user

  has_many :users, dependent: :destroy
  has_many :pay_codes, dependent: :destroy
  has_many :products, dependent: :destroy

  enum status: { disabled: 1, enabled: 0 }
end

app/models/site_user.rb
class SiteUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :site_bot, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:username]
  validates :username, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  # use this instead of email_changed? for Rails = 5.1.x
  def will_save_change_to_email?
    false
  end
end

app/models/treasure.rb
class Treasure < ApplicationRecord
  belongs_to :product
  LOCATIONS = %i[galician livandovka suhiv lichakiv shevchenkiv frankiv].freeze
  STATUSES = %i[available sold].freeze
  enum location: LOCATIONS
  enum status: STATUSES
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :site_bot
  enum choosen_location: Treasure::LOCATIONS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    sign_up_attrs = [:username, :tg_nickname, :password, :password_confirmation, :remember_me]
    sign_in_attrs = [:username, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: sign_up_attrs
    devise_parameter_sanitizer.permit :account_update, keys: sign_in_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # render html: cell(:home).(), layout: true
  end
end

app/controllers/site_bots_controller.rb
class SiteBotsController < ApplicationController
  before_action :authenticate_site_user!

  def create
    result = SiteBot::Create.call(params, {'current_user' => current_site_user}.with_indifferent_access)

    if result.success?
      redirect_to site_bot_path(result[:model])
    else
      render html: cell(:site_bot, result['contract.default']).(:new), layout: true
    end
  end

  def new
    render html: cell(:site_bot, SiteBot.new).(:new), layout: true
  end

  def show
    if current_site_user.site_bot.present?
      SiteBot::Show.call(params, {'current_user' => current_site_user}.with_indifferent_access)
      render html: cell(:site_bot, current_site_user.site_bot).(:show), layout: true
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BotTg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    params[:controller] %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Telegram Bot</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <% if current_site_user&.site_bot&.present? %>
              <%= link_to 'Мой бот', site_bot_path, class: 'nav-link'%>
            <% else %>
            <%= link_to 'Создать бота', new_site_bot_path, class: 'nav-link'%>
            <% end %>
          </li>
        </ul>
        <% if site_user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_site_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <%= link_to 'Выход', destroy_site_user_session_path, method: :delete %>
          </div>
        </li>
      </ul>
        <% else %>
          <%= link_to(:new_site_user_registration) do %>
            <button class="btn btn-outline-success my-2 my-sm-0 mr-2">Регистрация</button>
          <% end %>
          <%= link_to(:new_site_user_session) do %>
            <button class="btn btn-outline-success my-2 my-sm-0">Вход</button>
          <% end %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/site_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>